language: node_js
node_js:
  - 0.10
branches:
  only:
    - master
before_install:
  - sudo npm install -g hexo
install:
  - npm install
before_script:
  - git config --global user.name 'jKey Lu'
  - git config --global user.email 'jkeylu@gmail.com'
script:
  - git remote -v
  - git clone https://github.com/orderedlist/modernist.git themes/modernist
  - hexo generate
after_success:
  - hexo deploy --setup
  - git remote -v
  - hexo deploy
