language: node_js
node_js:
  - 0.10
branches:
  only:
    - master
before_install:
  - npm install -g hexo
install:
  - npm install
before_script:
  - git config --global user.name 'jKey Lu'
  - git config --global user.email 'jkeylu@gmail.com'
script:
  - git clone git://github.com/heroicyang/hexo-theme-modernist.git themes/hexo-theme-modernist
  - hexo generate
after_success:
  - hexo deploy
